In [376]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [377]:
data = datasets.load_breast_cancer()

In [378]:
df = pd.DataFrame(data.data[100:110])
df_target = pd.DataFrame(data.target[100:110])
df

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,13.610,24.98,88.05,582.7,0.09488,0.08511,0.08625,0.04489,0.1609,0.05871,...,16.99,35.27,108.60,906.5,0.1265,0.19430,0.31690,0.11840,0.2651,0.07397
1,6.981,13.43,43.79,143.5,0.11700,0.07568,0.00000,0.00000,0.1930,0.07818,...,7.93,19.54,50.41,185.2,0.1584,0.12020,0.00000,0.00000,0.2932,0.09382
2,12.180,20.52,77.22,458.7,0.08013,0.04038,0.02383,0.01770,0.1739,0.05677,...,13.34,32.84,84.58,547.8,0.1123,0.08862,0.11450,0.07431,0.2694,0.06878
3,9.876,19.40,63.95,298.3,0.10050,0.09697,0.06154,0.03029,0.1945,0.06322,...,10.76,26.83,72.22,361.2,0.1559,0.23020,0.26440,0.09749,0.2622,0.08490
4,10.490,19.29,67.41,336.1,0.09989,0.08578,0.02995,0.01201,0.2217,0.06481,...,11.54,23.31,74.22,402.8,0.1219,0.14860,0.07987,0.03203,0.2826,0.07552
5,13.110,15.56,87.21,530.2,0.13980,0.17650,0.20710,0.09601,0.1925,0.07692,...,16.31,22.40,106.40,827.2,0.1862,0.40990,0.63760,0.19860,0.3147,0.14050
6,11.640,18.33,75.17,412.5,0.11420,0.10170,0.07070,0.03485,0.1801,0.06520,...,13.14,29.26,85.51,521.7,0.1688,0.26600,0.28730,0.12180,0.2806,0.09097
7,12.360,18.54,79.01,466.7,0.08477,0.06815,0.02643,0.01921,0.1602,0.06066,...,13.29,27.49,85.56,544.1,0.1184,0.19630,0.19370,0.08442,0.2983,0.07185
8,22.270,19.67,152.80,1509.0,0.13260,0.27680,0.42640,0.18230,0.2556,0.07039,...,28.40,28.01,206.80,2360.0,0.1701,0.69970,0.96080,0.29100,0.4055,0.09789
9,11.340,21.26,72.48,396.5,0.08759,0.06575,0.05133,0.01899,0.1487,0.06529,...,13.01,29.15,83.99,518.1,0.1699,0.21960,0.31200,0.08278,0.2829,0.08832

In [379]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, df_target, test_size=0.2)
X_test

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
8,22.27,19.67,152.80,1509.0,0.13260,0.27680,0.42640,0.1823,0.2556,0.07039,...,28.40,28.01,206.80,2360.0,0.1701,0.69970,0.9608,0.29100,0.4055,0.09789
2,12.18,20.52,77.22,458.7,0.08013,0.04038,0.02383,0.0177,0.1739,0.05677,...,13.34,32.84,84.58,547.8,0.1123,0.08862,0.1145,0.07431,0.2694,0.06878

In [422]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

In [421]:
a = np.array_split(list(range(data.data.shape[0])), 5)
cv_list = [list(i) for i in a]

In [420]:
df = pd.DataFrame(data.data)
df_target = pd.DataFrame(data.target)

In [418]:
for i, item in enumerate(cv_list):
    X_test = np.array(df[df.index.isin(cv_list[i])])
    y_test = np.array(df_target[df_target.index.isin(cv_list[i])])

    X_train = np.array(df[df.index.isin(cv_list[i])==False])
    y_train = np.array(df_target[df_target.index.isin(cv_list[i])==False])
    dt.fit(X_train, y_train)
    y_pred = dt.predict(X_test)
    y_test.flatten()
    y_test = y_test.flatten()

    counter = 0
    for i in range(len(y_pred)):
        if y_test[i] == y_pred[i]:
            counter = counter + 1
    print('Accuracy: ', round(counter/len(y_pred),3))

Accuracy:  0.86
Accuracy:  0.921
Accuracy:  0.947
Accuracy:  0.921
Accuracy:  0.85